apiVersion: 1.0.0
kind: AssuranceProcedure
procedure:
  nrn: "nrn:procedure:rover-medical/rover-medicine-system"
  short: "Rover Medical System - Verification Procedure"
  description: |
    "Verifies the configutation and communcations between the Pet Medicine Application and it's database."
activity:
  - name: pet-medicine-app
    short: "Pet Medicine Application Configuration"
    description: |
      "Verify the Pet Medicine Application has the required configuration settings to
      ensure security and operational resilence control standards are met."
    action:
      - name: database-connection
        short: "Database Connection String"
        description: "The application connects to the databse at network location 'db://pet-medicine-db/prescriptions'."
        test: "activity/pet-medicine-app/database-connection.py"
        evidence: "evidence/pet-medicine-app/app-config.toml"